language: generic
sudo: required

services:
  - docker

env:
  global:
    - OTVERSION=1.16rc1

matrix:
  include:
    - env: PYVER=3.6
    - env: PYVER=3.7
    - env: PYVER=3.8
    - env: PYVER=3.9

install:
  - docker pull openturns/archlinux-mingw

script:
  - docker run -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-mingw /io/run_docker_build.sh ${OTVERSION} ${PYVER} `id -u` `id -g`

deploy:
  provider: releases
  api_key:
    secure: HvJyLF06qPvHC+vn6x8Kf2d9p5oxlxlGtQs9HcFdaVBBXahNs0/T3oEYZQYcmzHvNEWzZ1t8+1BEuddhsw60H7xIEwV3SiXyvxapfaMMdQQVtQg+lAK9j9ulMnMLDO5MupjJ5B1UeBTH2IWBTro4rCwaUPLiZMWlM/FCYJf0pmgVyVhl7ns88vfJFjxZKwaf8IhSS9+JjZKnfVgOlonJGNkdUWuqsrv3gGvVZElfYzA9NilmN1FVYuOPhiLe0Ok2l42mVrXQBFxgVD48gK+NXezQwDlr+W8Q0aWJ85sVS+C2MYNypZBm8WinF1X1DFZ39mhi/lawF0m4FDQR2f/Br1JmhlUREMZ+MmcXIur0W/453+juoncI7gkM7y41Lc023JVSCfoWKPcDsR1Vyr01IQ1cKTFnZZ0RnVaVAR50Dc2uXQgv+TkNe8GNVNIJ4hnCAfjftSj08bBT3ECx04FFDOT0Y8B72vHZgbtPiqwT25sJtDbFeZAlTQEIbZq+4wP7CfGkCSVJQvXQ2NXN2xzLQLmpwlaLY2ofI5bNy/W5bhIGtLeFdj850McXW85qsMU17MmxbZCSRlBTgkpmE37bQbc8P8PSQW2LEx7DSR5g8AwHimdXRyZRUWOy282w9KBCOgsnlXDPDROphjdYyFRUouLsGioDwju2FpPIqCF/RZI=
  file_glob: true
  file:
    - ${TRAVIS_BUILD_DIR}/*.exe
  repo: openturns/build-modules
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
