name: Release

on: push

jobs:
  mingw:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.20']
        pyver: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker pull openturns/archlinux-mingw && docker run -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-mingw /io/run_docker_build.sh ${{ matrix.version }} ${{ matrix.pyver }} `id -u` `id -g`
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            otagrum-0.7-py${{ matrix.pyver }}-x86_64.exe
            otfftw-0.12-py${{ matrix.pyver }}-x86_64.exe
            otmixmod-0.13-py${{ matrix.pyver }}-x86_64.exe
            otmorris-0.13-py${{ matrix.pyver }}-x86_64.exe
            otpmml-1.12-py${{ matrix.pyver }}-x86_64.exe
            otrobopt-0.11-py${{ matrix.pyver }}-x86_64.exe
            otsubsetinverse-1.9-py${{ matrix.pyver }}-x86_64.exe
            otsvm-0.11-py${{ matrix.pyver }}-x86_64.exe
